# Generated by Django 4.0.4 on 2022-05-20 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='dead_line',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
