# Generated by Django 4.0.4 on 2022-05-21 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_task_dead_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='other', max_length=22),
        ),
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(default=datetime.datetime(2022, 5, 21, 11, 40, 53, 383502, tzinfo=utc)),
        ),
    ]
