# Generated by Django 4.0.4 on 2022-05-22 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('family', 'Family'), ('work', 'Work'), ('garden', 'Garden'), ('household', 'Household'), ('other', 'Other')], default='other', max_length=21),
        ),
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 8, 40, 45, 18955, tzinfo=utc)),
        ),
    ]
