# Generated by Django 4.0.4 on 2022-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Must do', 'Must do'), ('Should do', 'Should do'), ('Nice to do', 'Nice to do')], default='normal', max_length=15),
        ),
    ]
