# Generated by Django 4.0.4 on 2022-05-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='name',
        ),
    ]
