# Generated by Django 4.0.4 on 2022-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_20220528_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Must do', 'Must do'), ('Should do', 'Should do'), ('Nice to do', 'Nice to do')], default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=25),
        ),
    ]
