# Generated by Django 4.0.4 on 2022-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_task_priority_alter_task_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
