# Generated by Django 4.0.4 on 2022-06-07 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_task_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to_do',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(),
        ),
    ]
