# Generated by Django 4.0.4 on 2022-05-29 15:09

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_task_to_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateTimeField(default=base.models.one_week_later),
        ),
    ]
