# Generated by Django 4.0.5 on 2022-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_task_dead_line_time_task_to_do_time_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='to_do_time',
            field=models.TimeField(),
        ),
    ]
